### ISSUE TITLE
Ticking block entity crash with hopper #129

### ISSUE THREAD

**Issue by Kellermanx** [BukkitFabric/bukkit4fabric#80] opened 2020-11-20 04:25 UTC
Sever carsh whenever players near the hopper area.

[crash-2020-11-20_12.20.27-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5571202/crash-2020-11-20_12.20.27-server.txt)

**Comment by fantahund** [comment] 2020-11-23 20:43
same bug:

`net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:874) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:810) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.class_2614.handler$zca000$extract2(class_2614.java:607) ~[intermediary-server.jar:?]
	at net.minecraft.class_2614.method_11261(class_2614.java) ~[intermediary-server.jar:?]
	at net.minecraft.class_2614.method_17768(class_2614.java:201) ~[intermediary-server.jar:?]
	at java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119) ~[?:?]
	at java.util.Spliterators$IntArraySpliterator.tryAdvance(Spliterators.java:1041) ~[?:?]
	at java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.IntPipeline.anyMatch(IntPipeline.java:513) ~[?:?]
	at net.minecraft.class_2614.method_11241(class_2614.java:201) ~[intermediary-server.jar:?]
	at net.minecraft.class_2614.method_31691(class_2614.java:104) ~[intermediary-server.jar:?]
	at net.minecraft.class_2614.method_11243(class_2614.java:120) ~[intermediary-server.jar:?]
	at net.minecraft.class_2614.method_31692(class_2614.java:104) ~[intermediary-server.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:839) ~[intermediary-server.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:894) ~[intermediary-server.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:485) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:417) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:870) ~[intermediary-server.jar:?]
	... 5 more`

**Comment by IsaiahPatton** [comment] 2020-11-25 06:20
crash fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/c9123e1dbc454e76448d0afb27bf83b461235e2c

**Closed by IsaiahPatton** 2020-11-25 06:20 UTC
Labels: fixed
