### ISSUE TITLE
 You can't use a fishing rod.

### ISSUE THREAD

**Issue by fantahund** [BukkitFabric/bukkit4fabric#74] opened 2020-11-15 19:42 UTC
You can't use a fishing rod.
no error in console

**Comment by L0rdLogan** [comment] 2020-11-15 20:23
Error re-produced, this is the console message I got: 

[20:22:21] [Server thread/FATAL]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.3;5407315
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Bukkit4Fabric-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:227) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3225.handler$zhn001$interactBlock(class_3225.java:799) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.handleBlockRightClick(WorldGuardPlayerListener.java:266) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerInteract(WorldGuardPlayerListener.java:227) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Bukkit4Fabric-1.16.4.jar:?]
        ... 23 more

**Comment by L0rdLogan** [comment] 2020-11-15 20:34
To add, a bizarre issue, I removed WorldGuard and WorledEdit plugin, it still wants to pass the even to WordGuard 7.0.3

[20:22:21] [Server thread/FATAL]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.3;5407315
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Bukkit4Fabric-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:227) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3225.handler$zhn001$interactBlock(class_3225.java:799) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.handleBlockRightClick(WorldGuardPlayerListener.java:266) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerInteract(WorldGuardPlayerListener.java:227) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Bukkit4Fabric-1.16.4.jar:?]
        ... 23 more[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.
[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.
[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.
[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.
[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.
[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.
[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.
[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.
[20:33:57] [Server thread/INFO]: Unknown command. Type "help" for help.

**Comment by IsaiahPatton** [comment] 2020-11-17 03:53
Fixing rod fixed in build 128

**Closed by IsaiahPatton** 2020-11-17 03:53 UTC
